POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo Evento 2",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/c7c2b569-4ecc-4670-a145-de85cc0ecb56/attendees
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john12@email.com"
}

###

GET http://localhost:3333/events/c7c2b569-4ecc-4670-a145-de85cc0ecb56
Content-Type: application/json

###

GET http://localhost:3333/attendees/1/badge
Content-Type: application/json

###

GET http://localhost:3333/attendees/5/check-in
Content-Type: application/json

###

GET http://localhost:3333/events/c7c2b569-4ecc-4670-a145-de85cc0ecb56/attendees?query=doe
Content-Type: application/json